language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

dist: xenial
group: edge

cache:
  directories:
    - vendor
  
script:
  - php vendor/bin/phpunit -v

before_script:
  - composer install --prefer-source

after_success:
  - travis_retry php vendor/bin/php-coveralls -v